name: fifth_exam
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  lottie: ^2.0.0
  connectivity_plus: ^3.0.2
  firebase_messaging: ^14.1.1
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  sqflite: ^2.2.3
  cloud_firestore: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
